---
title: "Incarceration Exploratory Analysis"
author: "Ben Aoki-Sherwood"
date: "2023-01-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
# library for downloading Census variables
library(tidycensus)

#for formatting data
library(tidyverse)
library(maditr)
library(patchwork)
library(broom)
#library(ggResidpanel)
```

# Load and clean data

```{r}
# load incarceration data
incarc_data <- read.csv("https://github.com/vera-institute/incarceration-trends/raw/master/incarceration_trends.csv")
incarc_cols <- c("county_name", "total_jail_pop_rate", "aapi_jail_pop_rate", 
                 "black_jail_pop_rate", "latinx_jail_pop_rate", 
                 "native_jail_pop_rate", "white_jail_pop_rate",
                 "total_pop_15to64", "aapi_pop_15to64", "black_pop_15to64",
                 "latinx_pop_15to64", "native_pop_15to64", "white_pop_15to64",
                 "urbanicity")

incarc_cols2 <- c("county_name", "total_jail_pop", "aapi_jail_pop", 
                 "black_jail_pop", "latinx_jail_pop", 
                 "native_jail_pop", "white_jail_pop",
                 "total_pop_15to64", "aapi_pop_15to64", "black_pop_15to64",
                 "latinx_pop_15to64", "native_pop_15to64", "white_pop_15to64",
                 "urbanicity")

# filter incarceration data to include only TX, 2018
# prepare county_name field as key for joining
tx_incarc <- incarc_data %>%
  filter(state == "TX" & year == 2018) %>%
  mutate(county_name = paste(county_name, ", Texas", sep = "")) %>%
  select(incarc_cols)

tx_incarc2 <- incarc_data %>%
  filter(state == "TX" & year == 2018) %>%
  mutate(county_name = paste(county_name, ", Texas", sep = "")) %>%
  select(incarc_cols2)
```

## Questions/Notes:

- Do we want median HOUSEHOLD (B19013) or median FAMILY (B19113) incomes?
- Per capita income is B19301
- Gini Index (inequality) is B19083

```{r}
# download ACS census data for Texas from 2018

# choose variables on Gini index (income inequality) and median household income by race
variables <- c("B19083_001E", "B19013_001E", "B19013A_001E", "B19013B_001E", 
               "B19013C_001E", "B19013D_001E", "B19013E_001E", "B19013F_001E", 
               "B19013G_001E", "B19013H_001E", "B19013I_001E")

tx_census <- get_acs(geography = "county", 
                     variables = variables, 
                     year = 2018,
                     state = "TX",
                     geometry = F)

code_book <- rbind(c("B19083_001", "gini_index"),
                   c("B19013_001", "household_income_all"),
                   c("B19013A_001", "household_income_white"),
                   c("B19013B_001", "household_income_black"),
                   c("B19013C_001", "household_income_native"),
                   c("B19013D_001", "household_income_asian"),
                   c("B19013E_001", "household_income_nhpi"),
                   c("B19013F_001", "household_income_other"),
                   c("B19013G_001", "household_income_two_races"),
                   c("B19013H_001", "household_income_white_not_hispanic"),
                   c("B19013I_001", "household_income_hispanic"))

#join to the Census data
code_book <- as.data.frame(code_book)
colnames(code_book) <- c("variable", "var_name")
tx_census <- left_join(tx_census, code_book)

#format the data so there is a row for each census tract and column for every variable
tx_acs_data <- maditr::dcast(tx_census, NAME ~ var_name, 
                               value.var = "estimate", 
                               fun.aggregate = NULL) %>%
  rename("county_name" = "NAME")
```

```{r}
# pivot data so we have (county, race) observations
# acs data:

long_acs <- tx_acs_data %>%
  select(-c("household_income_white", "household_income_other", 
            "household_income_two_races", "household_income_nhpi")) %>%
  pivot_longer(cols = c("household_income_all", "household_income_white_not_hispanic", 
                        "household_income_black",  "household_income_native", 
                        "household_income_asian", "household_income_hispanic"), 
               names_to = "race", 
               values_to = "median_household_income", 
               names_prefix = "household_income_") %>%
  # rename to match races between datasets
  mutate(race = str_replace(race, "_not_hispanic", ""), 
         race = str_replace(race, "hispanic", "latinx"))

# incarceration data:

long_incarc2 <- tx_incarc2 %>%
  rename_with(function (x) {str_replace(x, "_jail", ".jail")}) %>%
  rename_with(function (x) {str_replace(x, "_pop_15", ".pop_15")}) %>%
  filter(!(total.jail_pop != 0.0 & aapi.jail_pop == 0.0 & 
             black.jail_pop == 0.0 & latinx.jail_pop == 0.0 & 
             native.jail_pop == 0.0 & white.jail_pop == 0.0)) %>%
  pivot_longer(cols = c("total.jail_pop", "aapi.jail_pop", 
                        "black.jail_pop", "latinx.jail_pop", 
                        "native.jail_pop", "white.jail_pop",
                        "total.pop_15to64", "aapi.pop_15to64", "black.pop_15to64",
                        "latinx.pop_15to64", "native.pop_15to64", "white.pop_15to64"),
               names_to = c("race", ".value"), names_sep = "\\.") %>%
  # rename to match races between datasets
  mutate(race = str_replace(race, "aapi", "asian"),
         race = str_replace(race, "total", "all"))

# join datasets, drops NAs:
joined_data2 <- left_join(long_acs, long_incarc2, by = c("county_name", "race")) %>%
  drop_na()
```

# EDA

### controls

```{r}
# check relationship of controls (population, urbanicity) and EVs (median household income, Gini)
# with jail pop, the RV

# log transformed where necessary to get a linear-looking relationship
pop <- joined_data2 %>% ggplot(aes(x = log(pop_15to64), y = log1p(jail_pop))) + geom_point() +
  labs(x = "Log Population 15-64", y = "Log Jail Population", title = "Relationship between Log Jail Population and Log Population Ages 15-64 by Race in Texas Counties")
urb <- joined_data2 %>% ggplot(aes(x = urbanicity, y = log1p(jail_pop))) + geom_boxplot() +
  labs(x = "Urbanicity", y = "Log Jail Population", title = "Relationship between Log Jail Population and Urbanicity by Race in Texas Counties")
gini <- joined_data2 %>% ggplot(aes(x = gini_index, y = log1p(jail_pop))) + geom_point() +
  labs(x = "Gini Index", y = "Log Jail Population", title = "Relationship between Log Jail Population and Gini Index by Race in Texas Counties")
inc <- joined_data2 %>% ggplot(aes(x = median_household_income, y = log1p(jail_pop))) + geom_point() +
  labs(x = "Median Household Income, USD", y = "Log Jail Population", title = "Relationship between Log Jail Population and Median Household Income by Race in Texas Counties")

pop
urb
gini
inc
```

```{r, eval = FALSE}
# examine relationship between population for each race in each county and the 
# population of that race in jail in that county
joined_data %>%
  filter(race == "all") %>%
  ggplot(aes(x = log(pop_15to64), y = log1p(jail_pop))) +
    geom_point()
```


### race 

```{r}
# clear discrepancies between jail pop rates between races
joined_data2 %>% 
  ggplot(aes(x = race, y = log1p(jail_pop) - log(pop_15to64))) +
  geom_boxplot() +
    labs(y = "log(Jail Population Rate)", x = "Race", 
         title = "Jail Population Rate by Race for Texas Counties in 2018")
```


```{r}
# see if effect of population on jail population differs by race
joined_data2 %>% 
  ggplot(aes(x = log(pop_15to64), y = log1p(jail_pop), color = race)) +
    geom_point() +
    geom_smooth(method = "lm", se = F) +
    labs(x = "log(Population Ages 15-64)", y = "log(Jail Population)", color = "Race", 
         title = "Interaction between Race and Population of that race on Jail Population of that race in each County in Texas")
```

# fit model

```{r}
#null: just race and log(population)
null_model <- lm(log1p(jail_pop) ~ log(pop_15to64) + race, data = joined_data2)

#urb: add urbanicity
urb_model <- lm(log1p(jail_pop) ~ log(pop_15to64) + race + urbanicity, data = joined_data2)

#inc: add income
inc_model <- lm(log1p(jail_pop) ~ log(pop_15to64) + race + median_household_income, data = joined_data2)

#full: null with median household income and urbanicity added
full_model <- lm(log1p(jail_pop) ~ log(pop_15to64) + median_household_income + urbanicity + race, data = joined_data2)

# exploring possible interactions
interaction_model <- lm(log1p(jail_pop) ~ log(pop_15to64) + median_household_income*urbanicity + race, data = joined_data2)
interaction_model2 <- lm(log1p(jail_pop) ~ log(pop_15to64) + median_household_income + race*urbanicity, data = joined_data2)
final_model <- lm(log1p(jail_pop) ~ log(pop_15to64) + race*urbanicity, data = joined_data2)

aug_null <- augment(null_model, newdata = joined_data2)
aug_full <- augment(full_model, newdata = joined_data2)
aug_final <- augment(final_model, newdata = joined_data2)
```


```{r}
# check model assumptions
library(ggResidpanel)
ggplot(aug_null, aes(x = log(pop_15to64), y = .resid)) + geom_point()
ggplot(aug_null, aes(x = median_household_income, y = .resid)) + geom_point()
ggplot(aug_null, aes(x = race, y = .resid)) + geom_boxplot()
resid_xpanel(null_model)
resid_panel(null_model, plots = c("qq", "resid"))
```

```{r}
anova(null_model, urb_model) #urbanicity is significant (very close to 95%, so we'll call it good!)
anova(null_model, inc_model) #income not significant
anova(urb_model, full_model) #adding income once urbanicity is added is not significant

anova(full_model, interaction_model2)

anova(urb_model, final_model) #adding interaction is significant, but these interactions might not be meaningful: this seems like overfitting!
```

```{r}
#final model assumptions

library(ggResidpanel)
pop_resids <- ggplot(aug_final, aes(x = log(pop_15to64), y = .resid)) + geom_point() + labs(x = "log(Population)", y = "Residuals")
urb_resids <- ggplot(aug_final, aes(x = urbanicity, y = .resid)) + geom_boxplot() + labs(x = "Urbanicity", y = "Residuals")
race_resids <- ggplot(aug_final, aes(x = race, y = .resid)) + geom_boxplot() + labs(x = "Race", y = "Residuals")
final_qq <- ggplot(aug_final, aes(sample = .resid)) + geom_qq() + geom_qq_line() + labs(x = "Normal Quantiles", y = "Sample Quantiles", title = "QQ Plot")
assumptions <- (urb_resids + race_resids) / (final_qq + pop_resids) + plot_annotation(title = "Checking Model Assumptions", theme = theme(plot.title = element_text(size =20, color = "purple")))
assumptions

```

```{r}
# view final model coefficients and get 95% CIs for each 
summary(urb_model)
confint(urb_model)
```


